import MySQLdb
print('Conectando...')
conn = MySQLdb.connect(user='root', passwd='admin', host='127.0.0.1', port=3306)

# Descomente se quiser desfazer o banco...
conn.cursor().execute("DROP DATABASE if exists `pokefriends`;")
conn.commit()

criar_tabelas = '''SET NAMES latin1;
    CREATE DATABASE `pokefriends` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
    USE `pokefriends`;
    
    CREATE TABLE `countries` (
      `threecode` char(3) COLLATE utf8_bin NOT NULL,
      `name` varchar(50) COLLATE utf8_bin NOT NULL,
       PRIMARY KEY (threecode)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
    
    
    CREATE TABLE `trainer` (
      `code` varchar(12) NOT NULL COLLATE utf8_bin,
      `team` varchar(10) NOT NULL COLLATE utf8_bin,
      `country` varchar(20) NOT NULL COLLATE utf8_bin,
      `dateInserted` DATETIME not null,
      primary key (code),
      foreign key (country) references countries(threecode)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
    '''

conn.cursor().execute(criar_tabelas)
cursor = conn.cursor()
cursor.executemany(
      'INSERT INTO pokefriends.countries (`threecode`, `name`) VALUES (%s,%s)',
      [('WW', 'World Wide(ANY')
      ,('AFG','Afghanistan'),
('ALA','Åland'),
('ALB','Albania'),
('DZA','Algeria'),
('ASM','American Samoa'),
('AND','Andorra'),
('AGO','Angola'),
('AIA','Anguilla'),
('ATA','Antarctica'),
('ATG','Antigua and Barbuda'),('ARG','Argentina'),
('ARM','Armenia'),
('ABW','Aruba'),
('AUS','Australia'),
('AUT','Austria'),
('AZE','Azerbaijan'),
('BHS','Bahamas'),
('BHR','Bahrain'),
('BGD','Bangladesh'),
('BRB','Barbados'),
('BLR','Belarus'),
('BEL','Belgium'),
('BLZ','Belize'),
('BEN','Benin'),
('BMU','Bermuda'),
('BTN','Bhutan'),
('BOL','Bolivia'),
('BES','Bonaire'),
('BIH','Bosnia and Herzegovina'),
('BWA','Botswana'),
('BVT','Bouvet Island'),
('BRA','Brazil'),
('IOT','British Indian Ocean Territory'),
('VGB','British Virgin Islands'),
('BRN','Brunei'),
('BGR','Bulgaria'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('KHM','Cambodia'),
('CMR','Cameroon'),
('CAN','Canada'),
('CPV','Cape Verde'),
('CYM','Cayman Islands'),
('CAF','Central African Republic'),
('TCD','Chad'),
('CHL','Chile'),
('CHN','China'),
('CXR','Christmas Island'),
('CCK','Cocos [Keeling] Islands'),
('COL','Colombia'),
('COM','Comoros'),
('COK','Cook Islands'),
('CRI','Costa Rica'),
('HRV','Croatia'),
('CUB','Cuba'),
('CUW','Curacao'),
('CYP','Cyprus'),
('CZE','Czech Republic'),
('COD','Democratic Republic of the Congo'),
('DNK','Denmark'),
('DJI','Djibouti'),
('DMA','Dominica'),
('DOM','Dominican Republic'),
('TLS','East Timor'),
('ECU','Ecuador'),
('EGY','Egypt'),
('SLV','El Salvador'),
('GNQ','Equatorial Guinea'),
('ERI','Eritrea'),
('EST','Estonia'),
('ETH','Ethiopia'),
('FLK','Falkland Islands'),
('FRO','Faroe Islands'),
('FJI','Fiji'),
('FIN','Finland'),
('FRA','France'),
('GUF','French Guiana'),
('PYF','French Polynesia'),
('ATF','French Southern Territories'),
('GAB','Gabon'),
('GMB','Gambia'),
('GEO','Georgia'),
('DEU','Germany'),
('GHA','Ghana'),
('GIB','Gibraltar'),
('GRC','Greece'),
('GRL','Greenland'),
('GRD','Grenada'),
('GLP','Guadeloupe'),
('GUM','Guam'),
('GTM','Guatemala'),
('GGY','Guernsey'), ('GIN','Guinea'),
('GNB','Guinea-Bissau'),
('GUY','Guyana'),
('HTI','Haiti'),
('HMD','Heard Island and McDonald Islands'),
('HND','Honduras'),
('HKG','Hong Kong'),
('HUN','Hungary'),
('ISL','Iceland'),
('IND','India'),
('IDN','Indonesia'),
('IRN','Iran'),
('IRQ','Iraq'),
('IRL','Ireland'),
('IMN','Isle of Man'),
('ISR','Israel'),
('ITA','Italy'),
('CIV','Ivory Coast'),
('JAM','Jamaica'),
('JPN','Japan'),
('JEY','Jersey'),
('JOR','Jordan'),
('KAZ','Kazakhstan'),
('KEN','Kenya'),
('KIR','Kiribati'),
('XKX','Kosovo'),
('KWT','Kuwait'),
('KGZ','Kyrgyzstan'),
('LAO','Laos'),
('LVA','Latvia'),
('LBN','Lebanon'),
('LSO','Lesotho'),
('LBR','Liberia'),
('LBY','Libya'),
('LIE','Liechtenstein'),
('LTU','Lithuania'),
('LUX','Luxembourg'),
('MAC','Macao'),
('MKD','Macedonia'),
('MDG','Madagascar'),
('MWI','Malawi'),
('MYS','Malaysia'),
('MDV','Maldives'),
('MLI','Mali'),
('MLT','Malta'),
('MHL','Marshall Islands'),
('MTQ','Martinique'),
('MRT','Mauritania'),
('MUS','Mauritius'),
('MYT','Mayotte'),
('MEX','Mexico'),
('FSM','Micronesia'),
('MDA','Moldova'),
('MCO','Monaco'),
('MNG','Mongolia'),
('MNE','Montenegro'),
('MSR','Montserrat'),
('MAR','Morocco'),
('MOZ','Mozambique'),
('MMR','Myanmar [Burma]'),
('NAM','Namibia'),
('NRU','Nauru'),
('NPL','Nepal'),
('NLD','Netherlands'),
('NCL','New Caledonia'),
('NZL','New Zealand'),
('NIC','Nicaragua'),
('NER','Niger'),
('NGA','Nigeria'),
('NIU','Niue'),
('NFK','Norfolk Island'),
('PRK','North Korea'),
('MNP','Northern Mariana Islands'),
('NOR','Norway'),
('OMN','Oman'),
('PAK','Pakistan'),
('PLW','Palau'),
('PSE','Palestine'),
('PAN','Panama'),
('PNG','Papua New Guinea'),
('PRY','Paraguay'),
('PER','Peru'),
('PHL','Philippines'),
('PCN','Pitcairn Islands'),
('POL','Poland'),
('PRT','Portugal'),
('PRI','Puerto Rico'),
('QAT','Qatar'),
('COG','Republic of the Congo'),
('REU','Réunion'),
('ROU','Romania'),
('RUS','Russia'),
('RWA','Rwanda'),
('BLM','Saint Barthélemy'),
('SHN','Saint Helena'),
('KNA','Saint Kitts and Nevis'),
('LCA','Saint Lucia'),
('MAF','Saint Martin'),
('SPM','Saint Pierre and Miquelon'),
('VCT','Saint Vincent and the Grenadines'),
('WSM','Samoa'),
('SMR','San Marino'),
('STP','São Tomé and Príncipe'),
('SAU','Saudi Arabia'),
('SEN','Senegal'),
('SRB','Serbia'),
('SYC','Seychelles'),
('SLE','Sierra Leone'),
('SGP','Singapore'),
('SXM','Sint Maarten'),
('SVK','Slovakia'),
('SVN','Slovenia'),
('SLB','Solomon Islands'),
('SOM','Somalia'),
('ZAF','South Africa'),
('SGS','South Georgia and the South Sandwich Islands'),
('KOR','South Korea'),
('SSD','South Sudan'),
('ESP','Spain'),
('LKA','Sri Lanka'),
('SDN','Sudan'),
('SUR','Suriname'),
('SJM','Svalbard and Jan Mayen'),
('SWZ','Swaziland'),
('SWE','Sweden'),
('CHE','Switzerland'),
('SYR','Syria'),
('TWN','Taiwan'),
('TJK','Tajikistan'),
('TZA','Tanzania'),
('THA','Thailand'),
('TGO','Togo'),
('TKL','Tokelau'),
('TON','Tonga'),
('TTO','Trinidad and Tobago'),
('TUN','Tunisia'),
('TUR','Turkey'),
('TKM','Turkmenistan'),
('TCA','Turks and Caicos Islands'),
('TUV','Tuvalu'),
('UMI','U.S. Minor Outlying Islands'),
('VIR','U.S. Virgin Islands'),
('UGA','Uganda'),
('UKR','Ukraine'),
('ARE','United Arab Emirates'),
('GBR','United Kingdom'),
('USA','United States'),
('URY','Uruguay'),
('UZB','Uzbekistan'),
('VUT','Vanuatu'),
('VAT','Vatican City'),
('VEN','Venezuela'),
('VNM','Vietnam'),
('WLF','Wallis and Futuna'),
('ESH','Western Sahara'),
('YEM','Yemen'),
('ZMB','Zambia'),
('ZWE','Zimbabwe')])
      

# inserindo usuarios
cursor.executemany(
      'INSERT INTO pokefriends.trainer (code, team, country, dateinserted) VALUES (%s, %s, %s, %s)',
      [
            ('058450019208', 'VALOR' , 'BRA', '2021-03-05 14:00'),
            ('427492506440', 'MYSTIC', 'FRA', '2021-03-05 12:00')
      ])

cursor= conn.cursor()

cursor.execute('select * from pokefriends.trainer')
print(' -------------  Usuários:  -------------')
for user in cursor.fetchall():
    print(user[0])

cursor.execute('select * from pokefriends.countries')
print(' -------------  Jogos:  -------------')
for jogo in cursor.fetchall():
    print(jogo[1])

# commitando senão nada tem efeito
conn.commit()
cursor.close()